version: '3.8'

services:
  app:
    build: .
    container_name: career-rag-app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./chroma:/app/chroma
      - ./src:/app/src
    restart: unless-stopped
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    restart: unless-stopped